### ISSUE TITLE
NODE_ENV on windows

### ISSUE THREAD

**Issue by minasvisual** [evmizulin/cms-api#5]
Please, add node cross-env to "npm start" on windows to work NODE_ENV.

**Comment by NickCashFlow** [comment]
I also get this error
Please add node cross-env
here my logs
`
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cms-api@1.0.1~prestart: cms-api@1.0.1
6 info lifecycle cms-api@1.0.1~start: cms-api@1.0.1
7 verbose lifecycle cms-api@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle cms-api@1.0.1~start: PATH: C:\Users\RICH\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\projects\cms-api\node_modules\.bin;C:\Users\RICH\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\RICH\bin;C:\Ruby26-x64\bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\wGet;C:\ProgramData\chocolatey\bin;C:\Users\RICH\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\PuTTY;C:\Users\RICH\.windows-build-tools\python27;C:\Users\RICH\AppData\Roaming\npm;C:\Users\RICH\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle cms-api@1.0.1~start: CWD: D:\projects\cms-api
10 silly lifecycle cms-api@1.0.1~start: Args: [ '/d /s /c',
10 silly lifecycle   'NODE_ENV=development forever -w -c \'node --inspect\' index.js' ]
11 silly lifecycle cms-api@1.0.1~start: Returned: code: 1  signal: null
12 info lifecycle cms-api@1.0.1~start: Failed to exec start script
13 verbose stack Error: cms-api@1.0.1 start: `NODE_ENV=development forever -w -c 'node --inspect' index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\RICH\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\RICH\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cms-api@1.0.1
15 verbose cwd D:\projects\cms-api
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error cms-api@1.0.1 start: `NODE_ENV=development forever -w -c 'node --inspect' index.js`
22 error Exit status 1
23 error Failed at the cms-api@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

`
